Logging
compsci-adl/courses-api pull request #37
Opened 2024-10-16 08:52 UTC by SouthernPolaris

### Description
Added logging functionality instead of print statements. Also added them for some error messages

### Changes Made
Changed print statements marked #TODO with logging functionality. Added a new logging setup file which standardises the format of the logs across all included files. Appends error logs to an error text file for further review.

### Related Issues
Fixes issue 28

### Additional Notes
There appears to be an edge case with the courses api that made its way into the program before I even cloned the repo. The specific course id and details of the course causing issue is logged in the error logging file. I will raise an issue on it

2024-10-16 23:56 UTC, jsun969 requested changes

2024-10-16 23:56 UTC, jsun969 commented on src/db.json
Remove this file change

2024-10-16 23:56 UTC, jsun969 commented on src/error_log.txt
git ignore the error log

2024-10-16 23:56 UTC, jsun969 commented on src/log_setup.py
> +        error_file_handler = logging.FileHandler("error_log.txt", mode="w")
`error.log` for the file name will be better

2024-10-16 23:56 UTC, jsun969 commented on src/data_parser.py
> +                logger.debug(f"Course Details Not Found")
Error like "Not found" should be an error

2024-10-17 03:34 UTC, rayokamoto commented on src/error_log.txt
The error logs should be put into a `logs` directory. The name of the log file should also contain the timestamp, formatted like `YYYYMMDD-HHmmss.log`

2024-10-17 03:37 UTC, jsun969 commented on src/log_setup.py
> +        error_file_handler = logging.FileHandler("error_log.txt", mode="w")
https://github.com/compsci-adl/courses-api/pull/37#discussion_r1804057666

2024-11-12 01:34 UTC, phoenixpereira requested changes

2024-11-12 01:34 UTC, phoenixpereira commented on src/data_fetcher.py
> +        print(f"Fetching {self.endpoint}...")
Remove this to avoid clogging up the terminal when scraping.

2024-11-12 01:34 UTC, phoenixpereira commented on src/log_setup.py
This should also create the log file if it doesn't exist.

2024-11-12 01:34 UTC, phoenixpereira commented on src/log_setup.py
This should just ouput the debug statments to the log file rather than the both the log file and the console since this causes the console output to be too long and may cause a memory leak if using the VS Code terminal.

2024-11-12 01:34 UTC, phoenixpereira commented on src/log_setup.py
> +        error_formatter = logging.Formatter('\n%(asctime)s - %(levelname)s - %(message)s\n')
imo the log file can be debug level.

2024-11-15 02:11 UTC, closed without merging