Git Hook for Ruff
compsci-adl/courses-api pull request #52
Opened 2024-11-15 09:06 UTC by SouthernPolaris

### Description
Adds auto activation of ruff when a commit is made. Automatically performs a ruff --fix (which fixes both the "check" and "format" options at once)

### Changes Made
Added .pre-commit-config.yaml file

### Related Issues
Implements Issue 47: "[Feature Request] Add Git hook for Ruff"

2024-11-15 10:26 UTC, phoenixpereira requested changes

2024-11-15 10:26 UTC, phoenixpereira commented on src/data_fetcher.py
You should cherry-pick the commits to exclude the logging functionality commits as that's another PR

2024-11-15 10:26 UTC, phoenixpereira commented on .pre-commit-config.yaml
You need to add pre-commit as a dev dependency using uv.  Also, you'll need to update the README to include running `pre-commit install` to set the hook up unless there's a better way that only requires you to run`uv sync` to set it up.

2024-11-15 21:23 UTC, SouthernPolaris commented
Force pushed after pulling from upstream main to ensure it is not dependent on other pull request

2024-11-15 21:23 UTC, SouthernPolaris commented on .pre-commit-config.yaml
For now, I updated README, but I will look into uv sync to set it up automatically

2024-11-15 23:54 UTC, phoenixpereira requested changes

2024-11-15 23:54 UTC, phoenixpereira commented on README.md
> +Then, as recommended by [Official Pre-Commit Documentation](https://pre-commit.com/):
Reword to better highlight what this command is doing.
```suggestion
Install the git hook scripts:
```

2024-11-15 23:54 UTC, phoenixpereira commented on README.md
> +This should be run every time you clone a project
Not really relevant.
```suggestion
```

2024-11-15 23:54 UTC, phoenixpereira commented on README.md
> +```
We want to have pre-commit installed at a project level, so you can just do `uv add pre-commit --dev` and pre-commit should be installed when you do `uv sync`. You still need to do `pre-commit install` though to install the hook.

2024-11-15 23:54 UTC, phoenixpereira commented on README.md
> +This repository is configured with a pre-commit linting and formatting tool
Reword to better highlight what the pre-commit hook does.
```suggestion
This repository is configured with a pre-commit hook for automated linting and formatting.
```

2024-11-16 05:26 UTC, phoenixpereira approved these changes

2024-11-16 05:54 UTC, rayokamoto requested changes

2024-11-16 05:54 UTC, rayokamoto commented on .pre-commit-config.yaml
> +    - id: ruff-format
```suggestion
    - id: ruff-format

```

2024-11-16 06:44 UTC, rayokamoto approved these changes

2024-11-16 06:49 UTC, rayokamoto commented
> Implements Issue 47: "[Feature Request] Add Git hook for Ruff"

BTW, you can link issues to a pull request which will automatically resolve them once the PR is merged. [See more here](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue).

2024-11-17 00:40 UTC, merged