Refactor
compsci-adl/courses-api pull request #6
Opened 2024-08-11 09:24 UTC by hughmancoder

### Description
*Briefly describe the purpose of this pull request.*

### Changes Made
- Refactored and structured project to be more maintainable  
- Added Test suite to test current classes and establish good testing habits to avoid breaking changes
- Tested example data (https://github.com/compsci-adl/courses-api/issues/2)
- Added .git ignore template 
- Improved README
- Added makefile
- 

### Related Issues
N/A
*Reference any related issues using keywords like "Fixes #issue-number".*

### Additional Notes
*Add any other notes or screenshots that might be helpful for the reviewers.*
-tests passing

2024-08-11 10:02 UTC, phoenixpereira commented
Probably would need to wait until #4 and #5 are merged to do some more refactoring since those PR's would change multiple things.

2024-08-13 04:35 UTC, jsun969 commented
Please edit your PR title to describe what you did in this PR. TY!

2024-08-13 05:17 UTC, hughmancoder commented
> Please edit your PR title to describe what you did in this PR. TY!

- Done: descriptions are in changes made section

2024-08-13 05:26 UTC, jsun969 commented
It will be better if you follow https://github.com/compsci-adl/.github/blob/main/CONTRIBUTING.md#commit-messages to name your PR title.

2024-09-23 02:21 UTC, phoenixpereira commented
@hughmancoder Can you update your branch with main?

2024-09-23 05:01 UTC, hughmancoder commented
> @hughmancoder #4 and #5 have now been merged, so can you update your branch with main and make changes as needed?

Done. I've tested all the server routes and can confirm we get a response. Documentation updated too and unit tests passing

2024-09-23 10:04 UTC, phoenixpereira requested changes
Some changes needed for formatting and for the scraping to work.

2024-09-23 10:19 UTC, rayokamoto requested changes
In my opinion, the way the files have been split up into `api` and `db` folders do not make sense. This entire project **is** the API. We also don't have that many files so keeping it all under `src` makes sense. If we get way more files then it may make more sense to start splitting it up.

In addition, please format all of your files using Black.

Looks like Phoenix has already given some feedback so I'll just leave it at this for now.

2024-09-23 10:19 UTC, rayokamoto commented on src/main.py
Why does this exist if it's an empty file?

2024-09-23 10:19 UTC, rayokamoto commented on src/db/server.py
> +
Why are these commented out and not outright removed? Or if there is a chance they'll be used, just leave it uncommented. Generally not a fan of having dead code like this with no explanation.

2024-09-23 10:19 UTC, rayokamoto commented on README.md
> +poetry add tinydb
Yes

2024-09-23 10:56 UTC, phoenixpereira commented on src/db/server.py
We can do this in a seperate PR.

2024-09-25 11:34 UTC, phoenixpereira commented
@hughmancoder We made some changes to the project structure already to get the scraper working and make the server work with the api, so if you can make a separate PR just for adding testing that would be great.

2024-09-25 11:34 UTC, closed without merging